### ISSUE TITLE
What does `Socket Power` mean? Is this value correct?

### ISSUE THREAD

**Issue by HuaHuaY** [Umio-Yasuno/amdgpu_top#30]
![image](https://github.com/Umio-Yasuno/amdgpu_top/assets/41586196/da57dc13-d94a-4fb4-a554-99c4cb174d56)
Should this value be in mW?

**Comment by Umio-Yasuno** [comment]
Ok, I misunderstood.
`average_socket_power` in `gpu_metrics_v2_x` is usually mW, but in some Renoir/Lucienne/Cezanne/Barcelo APU and firmware combinations it is W.
The values in `gpu_metrics` is undocumented, so I need to read the source code of the AMDGPU driver to know the details.

Since `average_socket_power` seems to be almost the same as `GPU Power` in Sensors, I'm going to remove the code for `average_socket_power` in `gpu_metrics_v2_x`.
